import * as React from 'react';
interface UIFieldProps {
    className?: string;
    controlCss?: string;
    labelCss?: string;
    toggleCss?: string;
    fileCss?: string;
    rowCss?: string;
    errorCss?: string;
    helpCss?: string;
    label?: string | any;
    placeholder?: string;
    name?: string;
    help?: string | any;
    row?: string | boolean;
    password?: string | boolean;
    number?: string | boolean;
    date?: string | boolean;
    time?: string | boolean;
    range?: string | boolean;
    radio?: string | boolean;
    radios?: string | boolean;
    checkbox?: string | boolean;
    checkboxes?: string | boolean;
    select?: string | boolean;
    tagSelect?: string | boolean;
    singleSelect?: string | boolean;
    multiSelect?: string | boolean;
    custom?: any;
    options?: any[];
    toggle?: string | boolean;
    inline?: string | boolean;
    textarea?: string | boolean;
    file?: string | boolean;
    withPreview?: string | boolean;
    renderField?: (props?: any) => void;
    value?: any;
    onChange?: (val: any) => void;
    disabled?: boolean;
    validate?: any;
    children?: any;
    formik?: any;
}
declare const _default: React.ComponentType<UIFieldProps>;
export default _default;
